[project]
name = "azathoth"
authors = [
	{ name = "Fernando Bryan Reza Campos", email = "fer.rezac@outlook.com" },
]
version = "0.0.1"
description = "Some of the stuff I've created while learning the 'State of the Art' in AI."
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }
keywords = [ "ai", "mcp", "deep learning" ]
dependencies = [
	"rich>=14.2.0",
	"mcp[cli]>=1.20.0",
]

[tool.uv.workspace]
members = [
	"src/mcp_py*",
	"src/azathoth/*.py",
	# "src/azathoth*",  # this way it interprets azathoth as a package and it will need it's own pyproject.toml
]
exclude = [
	# pkg related
	"*.lock",
	"dist",
	"flake.*",

	# rust related stuff
	"Cargo.toml",
	"target",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[project.scripts]
azathoth = "azathoth:main"
# cli = "azathoth.cli:main"

mcp-py = "mcp_py:main"
main-tester = "mcp_py.examples.main_tester:main"

# * python mcp scripts
scout = "mcp_py.scout:main"
workflow = "mcp_py.workflow:main"

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"
