[project]
name = "azathoth"
authors = [
	{ name = "Fernando Bryan Reza Campos", email = "fer.rezac@outlook.com" },
]
version = "0.1.0"
description = "My personal AI architect and development partner."
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }
keywords = [ "ai", "mcp", "deep learning", "automation" ]
dependencies = [
	"rich>=14.2.0",
	"typer>=0.21.0",
	"mcp[cli]>=1.25.0",
	# Ingestion Dependencies
	"gitingest>=0.3.1",
	"httpx>=0.28.1",
	"nest-asyncio>=1.6.0", # Useful for running async code in CLI
]

[tool.uv.workspace]
members = [
	"src/mcp_py*",
	"src/azathoth/*.py",
	# "src/azathoth*",  # this way it interprets azathoth as a package and it will need it's own pyproject.toml
]
exclude = [
	"*.lock",
	"dist",
	"target",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[project.scripts]
azathoth = "azathoth:main"
# cli = "azathoth.cli:init_cli"

# mcp-py = "mcp_py:main"
# main-tester = "mcp_py.examples.main_tester:main"

# * python mcp scripts
scout = "mcp_py.scout:main"
workflow = "mcp_py.workflow:main"

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"
